layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

#projects:
#  sort_by: pushed
#  # sort_by options:
#  #   - pushed
#  #   - stars
#  limit: 9
#  exclude:
#    archived: false
#    forks: true
#    projects:
#    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
#   facebook: Haotian Fu
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: haotian-fu
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

cv_link: "/cv.html"

location: Shanghai, China

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning

  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning

  - name: Convex Optimization
    web_url: https://en.wikipedia.org/wiki/Convex_optimization

  - name: Pytorch
    web_url: https://github.com/pytorch/pytorch
    image_url: https://avatars.githubusercontent.com/u/21003710?s=48&amp;v=4

  - name: Skikit-learn
    web_url: https://github.com/topics/scikit-learn
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/scikit-learn/scikit-learn.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: LaTeX
    web_url: https://github.com/topics/latex
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/latex/latex.png

  - name: Markdown
    web_url: https://github.com/topics/markdown
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/markdown/markdown.png

bio:
  I am currently an undergraduate student majoring ECE.