profile:
  name: "Haotian Fu (付昊天)"
  title: "PhD Student in Computer Engineering, Stony Brook University"
  email: "haotian.fu01@gmail.com"
  location: "Stony Brook, NY, USA"
  avatar: "/assets/img/avatar.jpg"
